name: Publish to npm

on:
  push:
    tags:
      - 'v*.*.*'  # This will trigger the workflow for tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        yarn install
        yarn install-peers -f

    - name: Build (if necessary)
      run: yarn build

    - name: Set up .npmrc for yarn
      run: echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" > .npmrc
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Publish to npm
      run: yarn publish
